FROM node:24-alpine

WORKDIR /usr/src/app 

RUN corepack enable && corepack prepare pnpm@10.18.3 --activate 

COPY package.json pnpm-lock.yaml ./ 

RUN pnpm install --frozen-lockfile 

COPY . . 

EXPOSE 3000 

CMD ["pnpm", "run", "start:dev"]