FROM node:24-alpine AS build

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@10.18.3 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build


FROM node:24-alpine AS production

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@10.18.3 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --prod

COPY --from=build /usr/src/app/dist ./dist

EXPOSE 3000

CMD ["pnpm", "run" , "start:prod"]